### ISSUE TITLE
direct messages aren't working 

### ISSUE THREAD

**Issue by sanslash332** [ryanmcgrath/twython#515]
Hello,

I'm using twython 3.7.0 (indirectly) through a twitter client named "theqube"

WhenI'm trying to use any of the direct messages features, throws a twython exception, because the twitter sends a 404 not found because twithon is trying to connect to wrong api.

Exactly, the exception is this :

context; simple update command for get new direct messages.

TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist. 
Sun Apr 07, 2019 11:28:59 core.buffers.updating ERROR: tfj: Error during update process in buffer buffer Direct Messages 
Traceback (most recent call last): 
File "D:\Programacion\python\TheQube\src\core\sessions\buffers\buffers\updating.py", line 87, in update 
new = self.retrieve_update(update_type=update_type) 
File "D:\Programacion\python\TheQube\src\session\twitter\buffers\directs.py", line 25, in retrieve_update 
return self.timeline_update(update_function_name=’get_direct_messages’, since_id=self.get_max_twitter_id(), include_entities=True, full_text=True, tweet_mode=’extended’) 
File "D:\Programacion\python\TheQube\src\session\twitter\buffers\api_count.py", line 49, in timeline_update 
new_data = self.session.api_call(update_function_name, report_success=False, report_failure=False, *args, **kwargs) 
File "D:\Programacion\python\TheQube\src\session\twitter\twitter.py", line 415, in api_call 
raise e 
TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist. 

please tell me if the lib is outdated, or the client needs to update itself to use the new features of the twython lib.

%Thanks

**Comment by Menelion** [comment]
Hey @sanslash332, theQube maintainer here :). First of all, thanks for using the client! Basically, I don't have direct messages myself. I'm kind of against changing the library from Twython to something else, and also against embedding a patched version of Twython into my code. So, until #500 is merged, no direct messages for all of us :(.

**Comment by ryanmcgrath** [comment]
@mikehelmick is #500 cool with you?

**Comment by sanslash332** [comment]
so @menelion why not use directly the @manuelcortez fork into theqube instead this official package that is missing the #500 pr?

So, that Pr have more than 6 months waiting for an approval u.u

**Comment by mikehelmick** [comment]
Tagging @michaelhelmick instead.

**Comment by michaelhelmick** [comment]
#500 is merged, I'll try and get a release out this week!

**Comment by pyMixin** [comment]
was this fixed?

**Comment by brianwoo** [comment]
I am still getting this error: 
twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist.

**Comment by AgoraSecurity** [comment]
> I am still getting this error:
> twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist.

I get the same error

**Comment by fxlmo** [comment]
Is there a fix for this yet? Tried a lot of things and nothing has worked so far

**Comment by AgoraSecurity** [comment]
@fxlmo I couldn't find any. I migrated my project to another library :(

**Comment by ryanmcgrath** [comment]
I released the changes that were merged over the last... 2 years... and briefly tested things, DMs seemed to work for me.

I don't use this library in my personal work at the moment so if it's missing something it's still on the community to pull request it. Hope it helps tho. Thanks to all who've contributed!

**Comment by alexacallmebaka** [comment]
Is anyone else still having this issue? I am, and if we haven't found a clear fix, I may try for a pull request.
